name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Use this template to report bugs, issues, or unexpected behavior.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic or enhancement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - Database
        - Configuration
        - Git/Worktrees
        - Process Management
        - Tmux Integration
        - Web Backend
        - Web Frontend
        - GitHub Integration
        - Jira Integration
        - Notifications
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what the bug is
      placeholder: "A clear and concise description of what the bug is..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "A clear description of what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "A clear description of what actually happened..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: [e.g. macOS 14.5]
        - Python Version: [e.g. 3.11.5]
        - CC-Orchestrator Version: [e.g. 0.1.0]
        - Claude Code Version: [e.g. latest]

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: "Paste any relevant error messages or log output..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other context about the problem here..."
