name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template - Integration Analysis Required
        Use this template to report bugs, issues, or unexpected behavior.

        **🔗 MANDATORY READING Before Reporting:**
        - [Development Methodology](../../../DEVELOPMENT_METHODOLOGY.md) - Integration-First debugging approach
        - [Issue Context](../../../ISSUE_CONTEXT.md) - Project context and troubleshooting guides

        **⚠️ Integration Analysis:**
        Consider if this bug affects multiple components or breaks user workflows.
        Integration bugs often manifest as state inconsistencies across CLI/Web interfaces.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic or enhancement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - Database
        - Configuration
        - Git/Worktrees
        - Process Management
        - Tmux Integration
        - Web Backend
        - Web Frontend
        - GitHub Integration
        - Jira Integration
        - Notifications
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what the bug is
      placeholder: "A clear and concise description of what the bug is..."
    validations:
      required: true

  - type: textarea
    id: affected_workflow
    attributes:
      label: Affected User Workflow
      description: Which end-to-end user workflow is broken?
      placeholder: |
        Example: "Create instance → List instances → Stop instance → Verify stopped"

        At which step does the workflow fail?
        - [ ] Step 1: [User action]
        - [ ] Step 2: [System response]
        - [ ] Step 3: [User verification]
        - [ ] Step 4: [Final outcome]
    validations:
      required: true

  - type: textarea
    id: integration_impact
    attributes:
      label: Integration Impact Analysis
      description: Does this bug affect multiple components or break cross-component functionality?
      placeholder: |
        - [ ] Affects CLI only
        - [ ] Affects Web API only
        - [ ] Affects state persistence (data loss across invocations)
        - [ ] Breaks CLI ↔ Database integration
        - [ ] Breaks Web API ↔ Database integration
        - [ ] Breaks CLI ↔ Web API consistency
        - [ ] Affects process management integration
        - [ ] Other integration issue: [describe]

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (Integration-Focused)
      description: Include steps that test cross-component functionality
      placeholder: |
        1. [Action via CLI/Web]
        2. [Check state via different interface]
        3. [Perform related action]
        4. [Verify expected outcome]
        5. Observe error/inconsistency
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "A clear description of what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "A clear description of what actually happened..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: [e.g. macOS 14.5]
        - Python Version: [e.g. 3.11.5]
        - CC-Orchestrator Version: [e.g. 0.1.0]
        - Claude Code Version: [e.g. latest]

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: "Paste any relevant error messages or log output..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other context about the problem here..."
