blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/altsang/cc-orchestrator/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/altsang/cc-orchestrator/wiki
    about: Read the project documentation and guides