name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Lint with ruff
      run: |
        ruff check src/ tests/

    - name: Check formatting with black
      run: |
        black --check src/ tests/

    - name: Test with pytest
      env:
        JWT_SECRET_KEY: "test-secret-key-for-ci-cd-only-not-production"
        ENABLE_DEMO_USERS: "true"
        TESTING: "true"
      run: |
        pytest tests/ --cov=src --cov-report=xml --cov-fail-under=74

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml] "safety==2.3.5"

    - name: Run bandit security linter
      run: |
        bandit -r src/ -f json --configfile pyproject.toml

    - name: Check dependencies for security vulnerabilities
      run: |
        safety check
# Trigger CI/CD re-run Sat Aug 17 21:44:43 PDT 2025
